DefaultContentLanguage = "en"
theme = "hugo-xmag"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 6


[languages]
  [languages.en]
    title = "Smart Ag"
    weight = 1
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
      
      [permalinks]
        post = "/post/:year/:month/:day/:slug/"
    
        [[menu.main]]
            name = "Home"
            url = "/"
            weight = 1
        [[menu.main]]
            name = "About"
            url = "/about/"
            weight = 2
        [[menu.main]]
            name = "Categories"
            url = "/categories/"
            weight = 3
        [[menu.main]]
            name = "Tags"
            url = "/tags/"
            weight = 4
        [[menu.main]]
            name = "Subscribe"
            url = "/index.xml"
            weight = 5
        [[menu.main]]
            name = "中文"
            url = "/cn/"
            weight = 6
  
  [languages.cn]
    title = "Smart Ag"
    weight = 2
    [languages.cn.params]
      linkedin = "https://linkedin.com/fr/whoever"
      
       [[languages.cn.menu.main]]
            name = "主页"
            url = "/"
            weight = 1
        [[languages.cn.menu.main]]
            name = "关于"
            url = "/about/"
            weight = 2
        [[languages.cn.menu.main]]
            name = "类别"
            url = "/categories/"
            weight = 3
        [[languages.cn.menu.main]]
            name = "标签"
            url = "/tags/"
            weight = 4
        [[languages.cn.menu.main]]
            name = "订阅"
            url = "/index.xml"
            weight = 5
        [[languages.cn.menu.main]]
            name = "English"
            url = "/"
            weight = 6

[params]
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."
    summary_length = 300
    github_edit = "https://github.com/yihui/hugo-xmag/edit/master/exampleSite/content/"
    footer = "&copy; [CAU-CAB](https://cab.cau.edu.cn) 2019 | [Github](https://github.com/)"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
